name: API Auto Update  # The name of the workflow indicates its purpose to automatically update the API documentation.

on:  # Defines the events that trigger the workflow.
  push:
    branches: ["main"]  # This workflow is triggered by pushes to the 'dev' branch.
  workflow_dispatch:  # This allows the workflow to be manually triggered.

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:  # Defines a job called 'deploy'.
    runs-on: ubuntu-latest  # Specifies the virtual environment where the job will run.

    steps:  # Defines a list of steps to be executed.
      - name: Checkout  # Step to checkout the repository's code.
        uses: actions/checkout@v4  # Uses the actions/checkout action to access the repository code.

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Cache pip  # Step to cache pip packages.
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies  # Step to install dependencies.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build documentation
        run: |
          sphinx-build -b html . site
          
      - name: Create CNAME file
        run: echo "quairkit.com" > site/CNAME
        
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site